### PR TITLE
Add the TR7 Scheme interpreter

### PR DESCRIPTION
**Pull request by Irvise**
I am opening this PR in order to get an initial review going. I am sure that my way of doing things is far from acceptable. The TR7 interpreter, `tr7i` also does not currently run, it generated an `EACCESS` error even when running as root...

### CODE REVIEW

**Comment by streaksu** [comment]
Sorry for the delay, but Github review stopped working in Firefox? Its weird.

Some packages require gcc in their `imagedeps` as to do things like autoconf checks, this package does not seem to need it though. If thats the case, using it may cause issues, like using the host ar or gcc. Could you try removing it if not needed? Thanks in advance. Apart of that, it looks great.

**Comment by mintsuki** [comment]
The prefix should also be `/usr`, not `/usr/local`; preferrably by using the `${prefix}` variable.

**Comment by Irvise** [comment]
Thank you for your inputs. I have disabled the generation of a static library as, after removing `gcc` from `imagedeps` caused it to fail, and it was probably using the host `ar` instead of the target's `ar`. I have also updated the `prefix`. I used `/usr/local` as some programs were being installed there, such as `ed`, so I just followed suit with this... experimental port. Lastly, I have indicated that floating point printing is broken and will need some further investigation.

I tried building it and it does build, but it was giving me errors when it was trying to copy the generated binary telling me the target directory was read-only. I  updated my branch with upstream but it did not work. I am now running a full rebuild, which is going to take a while. But if you want, you can already test it for yourselves!

**Comment by streaksu** [comment]
> I tried building it and it does build, but it was giving me errors when it was trying to copy the generated binary telling me the target directory was read-only.

I checked the recipe and you are using `${prefix}`, but not `${dest_dir}`, which is needed for installation directories.
When building Gloire in a directory by the name of `/home/gloireuser/Gloire`, these variables will correspond to:

```bash
prefix = usr
dest_dir = /home/gloireuser/Gloire/pkgs/tr7/
```

Thus, they are needed for correct installation, else, it will be trying to install it in some other `/usr`, causing permission issues.

Thus, your install step should be

```bash
    install -v -D -t "${dest_dir}${prefix}"/bin tr7i
    # FIXME: maybe also compile and install share library?
    # install -v -D -t "${dest_dir}${prefix}"/lib libtr7.so*
    mkdir -p "${dest_dir}${prefix}"/include
    cp -r tr7libs "${dest_dir}${prefix}"/include
```

**Comment by Irvise** [comment]
Yup, that was it. I did a clean build of Gloire and TR7 now works as expected (with the known shortcomings) :)

If you like how things are, I believe it could be merged :)

**Comment by streaksu** [comment]
LGTM!

**Pull request merged**
